name: Dev

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Lint Project
      run: npm run lint --if-present

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Test Project
      run: npm run test --if-present
